require "user.config"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope_init"
require "user.session_manager"
require "user.treesitter"
require "user.shade"
require "user.lualine"
--[[ require "user.autopairs" ]]
require "user.comment"
require "user.nvimtree"
require "user.bufferline"
require "user.leap"
require "user.close_buffers"
require "user.undotree_init"
require "user.neotest"
--[[ require "user.noice" ]]
require "user.symbols_outline"
require "user.rainbow_csv"
